intel/vpl-gpu-rt

_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp

MFE is removed. to make sure ffmpeg working, skip MFE check.

[AVCe] Skip MFE check for backward compatiable

---

_studio/mfx_lib/encode_hw/shared/ehw_task_manager.cpp
_studio/mfx_lib/encode_hw/shared/ehw_task_manager.h

Frame skip after recode with parallel submission leads to getting stuck
in Prepare stage for one task and losing parallel submission.
Issue: MDP-62789
Test: manual, hevce_swbrc_slw_interlaced-plugin_hevcehw

[HEVCe/AV1e] Fix parallel submission in task manager

---

_studio/mfx_lib/encode_hw/mpeg2/include/mfx_mpeg2_encode_full_hw.h
_studio/mfx_lib/shared/include/mfx_mpeg2_encode_interface.h
_studio/mfx_lib/shared/src/mfx_mpeg2_encode_vaapi.cpp

Issue: MDP-66735
Tests: smt_mjpegd_mixe_1_n_async_ext-memory2

[mpeg2e] Call GetFrameHDL from FrameInterface (#1504)

---

_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp
_studio/mfx_lib/encode_hw/hevc/agnostic/g12/hevcehw_g12_caps.cpp

Remove vdenc422 restriction here, maxChroma can be controlled
by platform caps YUV422ReconSupport reported from driver.

[hevce/lib] Remove 422 VDEnc restriction

---

_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_impl.cpp
_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_interlace.cpp
_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_interlace.h
_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy.cpp

When the 1st field is skipped the 2nd one must be skipped too.
In this case the 2nd field should take the 1st one as a reference.
Issue: MDP-62788
Tested: manual

[hevce/swbrc] Fix the skipping of second fields

---

_studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp

Previously DDI caps for interlace were confused,
for VA_ENC_INTERLACED_FIELD (==2) ddi_caps.NoInterlacedField was set to 1,
which means that interlaced field IS NOT supported, and vice versa,
for VA_ENC_INTERLACED_NONE (==0) ddi_caps.NoInterlacedField was set to 0,
which means that interlaced field IS supported.

[AVCe] Correct VA Interlaced caps reading

---

.github/workflows/ubuntu.yml
CMakeLists.txt
_studio/mfx_lib/decode/h264/include/mfx_h264_dec_decode.h
_studio/mfx_lib/decode/h265/include/mfx_h265_dec_decode.h
_studio/mfx_lib/decode/mjpeg/include/mfx_mjpeg_dec_decode.h
_studio/mfx_lib/decode/vc1/include/mfx_vc1_decode.h
_studio/mfx_lib/decode/vp8/include/mfx_vp8_dec_decode_hw.h
_studio/mfx_lib/decode/vp9/include/mfx_vp9_dec_decode_hw.h
_studio/mfx_lib/shared/include/mfx_h264_encode_vaapi.h
_studio/mfx_lib/shared/src/libmfxsw.cpp
_studio/mfx_lib/vpp/include/mfx_vpp_main.h
_studio/mfx_lib/vpp/include/mfx_vpp_sw.h
_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
_studio/shared/include/libmfx_allocator.h
_studio/shared/include/mfx_umc_alloc_wrapper.h
_studio/shared/umc/codec/color_space_converter/include/umc_color_space_conversion.h
_studio/shared/umc/codec/color_space_converter/include/umc_deinterlacing.h
_studio/shared/umc/codec/color_space_converter/include/umc_video_processing.h
_studio/shared/umc/codec/h264_dec/include/umc_h264_frame.h
_studio/shared/umc/core/umc/include/umc_dynamic_cast.h
_studio/shared/umc/core/umc/include/umc_video_data.h
_studio/shared/umc/core/umc/include/umc_video_decoder.h

For: oneapi-src/oneVPL-intel-gpu#6
The following clang-12 warning still not addressed and got suppressed: `-Woverloaded-virtual`

ci: support clang-12 and fix errors and warnings

---

_studio/shared/include/mfx_config.h
_studio/shared/src/mfx_vpp_vaapi.cpp

`#undef MFX_ENABLE_VPP_FIELD_WEAVE_SPLIT ` will lead to different results between OS and CS.

[VPP] clean MFX_ENABLE_VPP_FIELD_WEAVE_SPLIT to align with CS

---

.github/workflows/ubuntu.yml

Fix: oneapi-src/oneVPL-intel-gpu#6
After the following fix in the core we can revert wa for clang-12:
* d1ab5c2 ("Core: partial clean up of OPAQ functions in CORE")
This reverts commit ee52257b18bb345408f610313bf41bd0a3cebae4.

Revert "ci: wa no-overloaded-virtual"

---

_studio/shared/umc/codec/jpeg_dec/src/mfx_mjpeg_task.cpp

when numScans > 3 in error clip, the program will get an out of bounds
read error.
Test: manually

[Jpegd] Fix the number of scan access out of bounds issue

---

_studio/shared/src/libmfx_core.cpp

- Fix Y210/Y216/Y416 to use mfxFrameInfo::Info.Shift

[core]: Fix FastCopy::CopyAndShift

---

.github/workflows/ubuntu.yml
_studio/shared/umc/core/vm/CMakeLists.txt
builder/FindInternals.cmake

Fixes: oneapi-src/oneVPL-intel-gpu#111
-Wl,--no-as-needed is actually a GNU Linker default (see man 1 ld), we
don't need to explicitly specify it on a linker cmdline. Especially
considering that some Linux distros on purpose build with the
-Wl,--as-needed instead.
-Wl,--as-needed looks to be stronger requirement than -Wl,--no-as-needed,
so it seems reasonable to use this as a default for our CI.
Finally, below build issue which we encounter with -Wl,--as-needed is
caused by missing -ldl for the internal library where we
actually use dlopen() stuff. We did have -ldl on a cmdline, but it was
at a wrong location, i.e. was added by cmake earlier than actually needed,
which caused link error.
[100%] Linking CXX shared library ../../__bin/None/libmfx-gen.so
/usr/bin/ld: …

build: fix build with -Wl,--as-needed

---

_studio/enctools/include/mfxenctools_dl_int.h

Fixes warnings on modern clang releases (12, 13)

Mark MFXDLVideoSession::DisjoinSession override

---

_studio/enctools/src/mfx_enctools_aenc.cpp

mfx_enctools_aenc.cpp:(.text+0x51e): undefined reference to `AEncUpdateFrame'
Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>

build: fix build failure due to missing AEncUpdateFrame

---

_studio/mfx_lib/encode_hw/av1/linux/base/av1ehw_base_va_packer_lin.cpp

Requires: intel/libva#608
Signed-off-by: RachelChengRJ <rachel.cheng@intel.com>

[Encode] AV1 Linux: remove WA for hierarchy flag

---

_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp

According to: https://github.com/intel/media-driver/blob/master/docs/media_features.md. Only VDENC supports RGB encoding, so use lowpower when input RGB data.

hevce: use Low Power mode for RGB encoding by default

---

_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp

Without this fix, the factor for detail filter is always 32 when the last buffer in the mfxExtBuffer list is not MFX_EXTBUFF_VPP_DETAIL.
Moreover if user doesn't provide MFX_EXTBUFF_VPP_DETAIL buffer, executeParams.bDetailAutoAdjust should be true.
Signed-off-by: Haihao Xiang <haihao.xiang@intel.com>

[VPP] correct the settings for detail filter

---

_studio/shared/src/mfx_vpp_vaapi.cpp

According to the description about mfxExtMasteringDisplayColourVolume, `MaxDisplayMasteringLuminance` is in units of 1 candela per square meter, `MinDisplayMasteringLuminance` is in units of 0.0001 candela per square meter. So only data.maxMasteringLuminance is multiplied by kLuminanceFixedPoint

[VPP] Correct the HDR meta data

---

_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp

Free() might be called multiple times, we should avoid double free in Free().

vpp: avoid double free

---

_studio/mfx_lib/encode_hw/mjpeg/include/mfx_mjpeg_encode_hw.h
_studio/mfx_lib/encode_hw/mjpeg/src/mfx_mjpeg_encode_hw.cpp
_studio/mfx_lib/encode_hw/mjpeg/src/mfx_mjpeg_encode_hw_utils.cpp
_studio/mfx_lib/shared/src/libmfxsw_encode.cpp
_studio/shared/include/mfxvideo++int.h
_studio/shared/src/libmfx_allocator_vaapi.cpp

The commit includes: 
1.  Fixed BGR4 JPEG Enc (api2x)
2. Enable YUV400 JPEG Enc (api1x and api2x)

Enable YUV400 JPEG Enc and BGR4 JPEG Enc (api2x)

---

_studio/shared/umc/codec/jpeg_common/include/bitstreamin.h
_studio/shared/umc/codec/jpeg_common/src/bitstreamin.cpp
_studio/shared/umc/codec/jpeg_dec/src/jpegdec_base.cpp

Use C++ std::string::find function to look for specific byte quickly.
When there is a lot of junk data in the jpeg stream, it took quite some time to look for the 0xff and the marker.
Try using C++ std::string find function to look for that; it greatly improve the speed.

[jpegd] Add quick seek function to bitstream

---

_studio/mfx_lib/decode/av1/src/mfx_av1_dec_decode.cpp
_studio/shared/umc/codec/av1_dec/include/umc_av1_dec_defs.h
_studio/shared/umc/codec/av1_dec/include/umc_av1_decoder.h
_studio/shared/umc/codec/av1_dec/src/umc_av1_bitstream.cpp
_studio/shared/umc/codec/av1_dec/src/umc_av1_decoder.cpp

User may get video signal info via MFX_EXTBUFF_VIDEO_SIGNAL_INFO buffer when calling MFXVideoDECODE_DecodeHeader() for H.264, H.265 etc, let's add the support for AV1 too.

av1d: add support for MFX_EXTBUFF_VIDEO_SIGNAL_INFO

---

CMakeLists.txt
_studio/mfx_lib/encode_hw/av1/linux/base/av1ehw_base_va_lin.cpp

if there are extCodingOption3 from user, vpl should respect user setting
also promote version to 23.4.5

[Av1e/lib]correct chrome format by the user parameter from upper layer

---

_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp

This commit is planned to remove double copying to/from GPU in hwupload and hwdownload.
It was tested on VPL GPU Runtime 2024Q4 Release - 24.4.4 and also on top of main branch.
And it was successful there.
It gave performance gain of 16-21% for below command line:
ffmpeg \
-qsv_device /dev/dri/renderD128 -hwaccel qsv \
-pix_fmt yuv422p10le -video_size 1920x1080 -i /videos/1920x1080p10le_1.yuv \
-pix_fmt yuv422p10le -video_size 1920x1080 -i /videos/1920x1080p10le_1.yuv \
-pix_fmt yuv422p10le -video_size 1920x1080 -i /videos/1920x1080p10le_1.yuv \
-pix_fmt yuv422p10le -video_size 1920x1080 -i /videos/1920x1080p10le_1.yuv \
-pix_fmt yuv422p10le -video_size 1920x1080 -i /videos/1920x1080p10le_1.yuv \
-pix_fmt yuv422p10le -video_size 1920x1080 -i /videos/1920x1080p10le_1.yuv \
-pix_fmt …

Remove double copy to/from GPU in hwupload and hwdownload
