intel/vpl-gpu-rt

_studio/shared/src/mfx_umc_alloc_wrapper.cpp

A proper fix is to keep assignment of internal surface (for original)
resolution and of external surface (for resized resolution) in the same function (which actually means at the
same timeframe).
Issue: MDP-66017
Test: runs with test_d_f20.265

[Decode]Fix VDBOX SFC output frame order issue

---

_studio/mfx_lib/decode/mjpeg/include/mfx_mjpeg_dec_decode.h
_studio/mfx_lib/vpp/CMakeLists.txt
_studio/mfx_lib/vpp/include/mfx_vpp_jpeg_d3d.h
_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
_studio/mfx_lib/vpp/src/mfx_vpp_jpeg_d3d.cpp
_studio/mfx_lib/vpp/src/mfx_vpp_sw_core.cpp
_studio/shared/include/libmfx_core.h
_studio/shared/include/mfx_vpp_interface.h
_studio/shared/src/mfx_umc_alloc_wrapper.cpp
_studio/shared/src/mfx_umc_mjpeg_vpp.cpp

Align OS code to CS.
Signed-off-by: Jay Yang jay.yang@intel.com

[VPP] OS/CS alignment

---

_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
_studio/mfx_lib/vpp/src/mfx_vpp_sw_internal.cpp
_studio/mfx_lib/vpp/src/mfx_vpp_utils.cpp
_studio/shared/include/mfx_vpp_interface.h
_studio/shared/include/mfx_vpp_vaapi.h
_studio/shared/src/mfx_vpp_vaapi.cpp
api/vpl/mfxdefs.h
api/vpl/mfxstructures.h

Signed-off-by: Furong Zhang <furong.zhang@intel.com>

Added 3DLUT Linux implementation in VPP.

---

CMakeLists.txt

[Media Common] Bump up version to 21.2.3

---

_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_interlace.cpp

[hevce/swbrc] Fix the skipping of second fields (update)

---

_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp

Switch to HORIZONTAL w/ warning

[AVCe] Non-overlapping Rolling-I is not supported

---

CODEOWNERS

Signed-off-by: Dmitry Ermilov <dmitry.ermilov@intel.com>

Added component code owners

---

_studio/shared/include/libmfx_allocator.h

surface_array: AddRef / Release owned surfaces

---

_studio/mfx_lib/CMakeLists.txt
_studio/shared/include/mfx_vpp_helper.h
_studio/shared/src/mfx_vpp_helper.cpp

Add VPP helper for easy use of VP features such as scaling, DN, etc.
Port from CS.
Issue: -
Test: -

[VPP] Add VPP helper for VPP features

---

_studio/shared/include/mfx_config.h
_studio/shared/include/mfx_config_decode.h
_studio/shared/include/mfx_config_encode.h
_studio/shared/include/mfx_config_vpp.h
_studio/shared/umc/CMakeLists.txt

Move decode specific feature macro def into mfx_config_decode.
Setup stub mfx_config_encode and mfx_config_vpp

Centralize feature macro def

---

_studio/enctools/include/mfx_enctools_lpla.h
_studio/enctools/src/mfx_enctools_common.cpp
_studio/enctools/src/mfx_enctools_lpla.cpp
_studio/mfx_lib/encode_hw/CMakeLists.txt
_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_data.h
_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_enctools.cpp
_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_enctools.h
_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_impl.cpp
_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_interlace.cpp
_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy.cpp
_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy.h
_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp
_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_max_frame_size.cpp
_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_roi.cpp
_studio/mfx_lib/encode_hw/hevc/linux/base/hevcehw_base_lin.cpp
_studio/mfx_lib/encode_hw/hevc/linux/base/hevcehw_base_va_lin.cpp
_studio/shared/include/mfx_config.h

[EncTools] Enable EncTools, add ET BRC for HEVCe

---

_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils.cpp
_studio/mfx_lib/encode_hw/shared/ehw_resources_pool.cpp
_studio/shared/include/libmfx_core.h
_studio/shared/include/mfxvideo++int.h
_studio/shared/src/libmfx_core.cpp

This function causes WRN in clang12 build

Core: partial clean up of OPAQ functions in CORE

---

_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp

[Hevce/lib] Refine code comments

---

_studio/mfx_lib/decode/vc1/include/mfx_vc1_decode.h
_studio/shared/umc/codec/h265_dec/include/umc_h265_frame.h
_studio/shared/umc/codec/h265_dec/src/umc_h265_frame_info.cpp
_studio/shared/umc/codec/h265_dec/src/umc_h265_mfx_utils.cpp
_studio/shared/umc/codec/h265_dec/src/umc_h265_task_supplier.cpp
_studio/shared/umc/codec/vc1_dec/include/umc_vc1_dec_task_store.h
_studio/shared/umc/core/umc/include/umc_video_decoder.h

[Decode] Comments refinement

---

_studio/mfx_lib/shared/include/mediasdk_version.h
contrib/ipp/include/owndefs.h

Signed-off-by: LijuanWang <lijuan.wang@intel.com>

[VPL] Refine the comments

---

_studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h
_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
_studio/mfx_lib/encode_hw/mpeg2/include/mfx_mpeg2_encode_full_hw.h
_studio/mfx_lib/encode_hw/mpeg2/include/mfx_mpeg2_encode_utils_hw.h
_studio/mfx_lib/shared/include/mfx_mpeg2_enc_common.h
_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
_studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
_studio/mfx_lib/shared/src/mfx_mpeg2_encode_vaapi.cpp

[Encode] Comments refinement

---

README.md

Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>

doc: clarify oneVPL usage in readme

---

CMakeLists.txt

[Media Common] Bump up version to 21.3.0

---

_studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_hw.cpp

Fix vp8d regression in #92

---

_studio/mfx_lib/decode/av1/src/mfx_av1_dec_decode.cpp
_studio/mfx_lib/decode/h264/src/mfx_h264_dec_decode.cpp
_studio/mfx_lib/decode/h265/src/mfx_h265_dec_decode.cpp
_studio/mfx_lib/decode/mjpeg/src/mfx_mjpeg_dec_decode.cpp
_studio/mfx_lib/decode/mpeg2/hw/src/mfx_mpeg2_decode.cpp
_studio/mfx_lib/decode/vc1/src/mfx_vc1_decode.cpp
_studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_hw.cpp
_studio/mfx_lib/decode/vp9/include/mfx_vp9_dec_decode_hw.h
_studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode_hw.cpp
_studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h
_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw_utils_new.cpp
_studio/mfx_lib/encode_hw/mjpeg/include/mfx_mjpeg_encode_hw.h
_studio/mfx_lib/encode_hw/mjpeg/include/mfx_mjpeg_encode_hw_utils.h
_studio/mfx_lib/encode_hw/mjpeg/src/mfx_mjpeg_encode_hw.cpp
_studio/mfx_lib/encode_hw/mjpeg/src/mfx_mjpeg_encode_hw_utils.cpp
_studio/mfx_lib/encode_hw/mpeg2/include/mfx_mpeg2_encode_full_hw.h
_studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw.h
_studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_ddi.h
_studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw.cpp
_studio/mfx_lib/shared/include/mfx_h264_enc_common_hw.h
_studio/mfx_lib/shared/include/mfx_h264_encode_interface.h
_studio/mfx_lib/shared/include/mfx_mpeg2_encode_interface.h
_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
_studio/mfx_lib/vpp/include/mfx_vpp_hw.h
_studio/mfx_lib/vpp/src/mfx_vpp_hw.cpp
_studio/shared/include/libmfx_core.h
_studio/shared/include/libmfx_core_interface.h
_studio/shared/include/mfx_vpp_interface.h

Signed-off-by: Dmitry Ermilov <dmitry.ermilov@intel.com>

Code alignment

---

_studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_ddi.h
_studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_par.cpp
_studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_vaapi.cpp

Need to merge after Driver change
Test: vp9_vdenc CI

[VP9e] Added MaxNumRef caps (#578)

---

_studio/mfx_lib/cmrt_cross_platform/include/cmrt_cross_platform.h
_studio/mfx_lib/cmrt_cross_platform/include/cmvm.h
_studio/mfx_lib/cmrt_cross_platform/src/cmrt_cross_platform.cpp

cmrt: align macro with streamline model

---

_studio/mfx_lib/shared/src/libmfxsw_decode_vp.cpp
_studio/shared/include/libmfx_allocator.h
_studio/shared/include/libmfx_allocator_vaapi.h
_studio/shared/include/libmfx_core.h
_studio/shared/src/libmfx_allocator.cpp
_studio/shared/src/libmfx_allocator_vaapi.cpp
_studio/shared/src/mfx_umc_alloc_wrapper.cpp

Keep surface with non-zero refcount even if session is closed
Issue: none
Test: manual

allocator: improve refcount logic (#2290)

---

.github/workflows/ubuntu.yml

Signed-off-by: Dmitry Rogozhkin <dmitry.v.rogozhkin@intel.com>

ci: switch to clang-12/13

---

_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp

Enable input with width/height unaligned at 16

[AVCe] Enable unaligned at 16 input

---

_studio/mfx_lib/decode/vp8/src/mfx_vp8_dec_decode_hw.cpp
_studio/mfx_lib/decode/vp9/src/mfx_vp9_dec_decode_hw.cpp
_studio/mfx_lib/encode_hw/hevc/linux/base/hevcehw_base_va_lin.cpp
_studio/mfx_lib/scheduler/linux/src/mfx_scheduler_core_thread.cpp
_studio/mfx_lib/shared/src/libmfxsw.cpp
_studio/mfx_lib/shared/src/libmfxsw_async.cpp
_studio/mfx_lib/shared/src/libmfxsw_decode.cpp
_studio/mfx_lib/shared/src/libmfxsw_encode.cpp
_studio/mfx_lib/shared/src/libmfxsw_vpp.cpp
_studio/shared/include/mfx_trace.h
_studio/shared/mfx_trace/CMakeLists.txt
_studio/shared/mfx_trace/src/mfx_trace_ir.cpp
_studio/shared/src/cm_mem_copy.cpp
_studio/shared/umc/codec/av1_dec/src/umc_av1_decoder_va.cpp
_studio/shared/umc/codec/h264_dec/include/umc_h264_segment_decoder_dxva.h
_studio/shared/umc/codec/h265_dec/include/umc_h265_segment_decoder_dxva.h
_studio/shared/umc/codec/mpeg2_dec/src/umc_mpeg2_decoder_va.cpp
_studio/shared/umc/io/umc_va/src/umc_va_linux.cpp

Signed-off-by: Dmitry Ermilov <dmitry.ermilov@intel.com>

Perf events

---

_studio/enctools/include/mfx_enctools.h
_studio/enctools/include/mfx_enctools_lpla.h
_studio/enctools/src/mfx_enctools_aenc.cpp
_studio/enctools/src/mfx_enctools_allocator.cpp
_studio/enctools/src/mfx_enctools_brc.cpp
_studio/enctools/src/mfx_enctools_common.cpp
_studio/enctools/src/mfx_enctools_lpla.cpp

[EncTools] Refactor VPP

---

_studio/mfx_lib/shared/src/libmfxsw_enc.cpp
_studio/mfx_lib/shared/src/libmfxsw_pak.cpp
_studio/mfx_lib/shared/src/libmfxsw_plugin.cpp

Fix confused syntax

---

_studio/enctools/src/mfx_enctools_common.cpp

[EncTools] Fix QueryPlatform call for LPLA

---

_studio/enctools/include/mfx_enctools.h
_studio/enctools/src/mfx_enctools_allocator.cpp
_studio/enctools/src/mfx_enctools_lpla.cpp
_studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h
_studio/mfx_lib/encode_hw/h264/src/mfx_h264_encode_hw.cpp
_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_data.h
_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy.cpp
_studio/mfx_lib/encode_hw/mpeg2/include/mfx_mpeg2_encode_utils_hw.h
_studio/mfx_lib/encode_hw/mpeg2/src/mfx_mpeg2_encode_utils_hw.cpp
_studio/mfx_lib/encode_hw/vp9/include/mfx_vp9_encode_hw_utils.h
_studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw.cpp
_studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_par.cpp
_studio/mfx_lib/encode_hw/vp9/src/mfx_vp9_encode_hw_utils.cpp
_studio/mfx_lib/shared/include/mfx_mpeg2_enc_common_hw.h
_studio/mfx_lib/shared/src/libmfxsw.cpp
_studio/mfx_lib/shared/src/libmfxsw_decode.cpp
_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp
_studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp
_studio/mfx_lib/shared/src/mfx_mpeg2_encode_vaapi.cpp
_studio/shared/include/mfx_h264_ex_param_buf.h

Signed-off-by: LijuanWang <lijuan.wang@intel.com>

[Encode] code alignment

---

CMakeLists.txt

[Media Common] Bump up version to 21.3.1

---

_studio/mfx_lib/encode_hw/hevc/agnostic/base/hevcehw_base_legacy_defaults.cpp

[HEVCe] enable BGR

---

_studio/mfx_lib/encode_hw/h264/include/mfx_h264_encode_hw_utils.h

Signed-off-by: LijuanWang <lijuan.wang@intel.com>

[AVCe] Update constructor for DdiTask2ndField

---

_studio/mfx_lib/shared/src/mfx_h264_enc_common_hw.cpp

[AVCe] Separate max and default active refs

---

_studio/enctools/CMakeLists.txt
_studio/enctools/aenc/include/aenc.h
_studio/shared/include/mfx_config_encode.h

Signed-off-by: LijuanWang <lijuan.wang@intel.com>

[Enctools] Macro centralization

---

_studio/mfx_lib/shared/include/mfx_frames.h
_studio/shared/include/libmfx_allocator_vaapi.h
_studio/shared/include/libmfx_core.h
_studio/shared/include/mfx_trace.h
_studio/shared/include/mfx_utils.h
_studio/shared/include/mfxstructures-int.h
_studio/shared/src/libmfx_allocator_vaapi.cpp
_studio/shared/src/libmfx_core.cpp
_studio/shared/src/libmfx_core_vaapi.cpp
_studio/shared/umc/core/umc/include/umc_frame_allocator.h
_studio/shared/umc/core/umc/include/umc_memory_allocator.h
_studio/shared/umc/core/umc/include/umc_va_base.h
_studio/shared/umc/io/umc_va/src/umc_va_linux.cpp

Issue: MDP-67484
Test: Not needed

[common] Comments refinement

---

_studio/enctools/include/mfx_enctools_defs.h
_studio/mfx_lib/lpla/mfx_lp_lookahead.cpp

[EncTools] Comment refinement

---

CMakeLists.txt

[Media Common] Bump up version to 21.3.2

---

.github/workflows/ubuntu.yml
_studio/shared/mfx_logging/include/mfx_utils_logging.h

Fixes: https://github.com/oneapi-src/oneVPL-intel-gpu/issues/196

build: fix build with gcc-11

---

_studio/mfx_lib/encode_hw/av1/agnostic/base/av1ehw_base_packer.cpp
_studio/mfx_lib/encode_hw/av1/agnostic/base/av1ehw_base_packer.h

[AV1e] Fix clang compiler warning

---

_studio/shared/src/mfx_vpp_vaapi.cpp

Correctly Map the 3DLUT system memory into the video memory for VAAPI

---

README.md

Enable Lunar Lake decoding and video processing support, encode will be
later.
Fixes: #346

Add Lunar Lake platform support
